# Header
menu:
  # home: /

extmenu:   
  GitHub: //github.com/bearpaw/
  Google Scholar: https://scholar.google.com/citations?user=6QQX88UAAAAJ
  Slides: /presentation/

# Content
excerpt_link: Read More

fancybox: false

# Miscellaneous
favicon: /images/favicon.png
google_analytics: UA-64554662-1
google_universal_analytics: 
rss:
