# Header
menu:
#  home: /

extmenu:
  GitHub: //github.com/bearpaw/
  Google+: //plus.google.com/+WeiYangplatero/

# Content
excerpt_link: Read More

fancybox: false

# Miscellaneous
google_analytics: UA-64554662-1
google_universal_analytics: 
rss:
